name: Build GUI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: icfpc-primary
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: rust
      run: |
          rustup target add x86_64-unknown-linux-musl
          # cargo test
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build
    - name: npm
      run: |
          cd ./gui
          npm install
          npm run build
    - name: upload
      run: |
          gsutil -m cp -r ./dist/* \
              gs://icfpc2021/gui
