name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: icfpc-primary
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Build
      run: |
          rustup target add x86_64-unknown-linux-musl
          cargo vendor
          cargo test
          cargo build --release
          gsutil -m cp -r ./target/release/{wata,wata_rnd,chokudai,chokudai_v1,dp,calculate_score} \
              gs://icfpc2021/artifacts/$(git rev-parse --short HEAD)/
